# Generated by Django 4.1.4 on 2023-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_food_imagepath"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
    ]
