# Generated by Django 4.1.4 on 2023-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_userlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="mail_id1",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
